FROM python:latest

ENV DATA_FILE /ex1data1.txt
ENV EPOCH_COUNT 1500
ENV LEARNING_RATE 0.01
ENV TEST_POPULATION_SIZE 3.5

COPY * /
RUN pip install pandas
RUN pip install matplotlib

CMD python Linear_Regression.py DATA_FILE=${DATA_FILE} EPOCH_COUNT=${EPOCH_COUNT} LEARNING_RATE=${LEARNING_RATE} TEST_POPULATION_SIZE=${TEST_POPULATION_SIZE}